# 파이썬 디자인 패턴

환영합니다! 저는 Brandon Rhodes입니다 ([웹사이트](https://rhodesmill.org/brandon/), [트위터](https://twitter.com/brandon_rhodes)). 이것은 [파이썬 프로그래밍 언어](https://www.python.org/)의 디자인 패턴에 대한 저의 발전적인 가이드입니다.

- 이 사이트를 통해 파이썬과 디자인 패턴에 대한 제 아이디어를 한곳에 모을 수 있게 되었습니다.
- 이 페이지들이 웹 검색에서 더 쉽게 찾을 수 있고, 제 [파이썬 컨퍼런스 강연](http://rhodesmill.org/brandon/talks/)의 비디오와 슬라이드에 흩어져 있을 때보다 더 쉽게 읽을 수 있도록 하여 패턴을 더 발견하기 쉽게 만들기를 바랍니다.
- 새로운 자료를 확인하려면, 이 사이트의 [GitHub 프로젝트 저장소](https://github.com/partrita/python-patterns)를 방문하시면 됩니다. 거기서 "Watch"를 선택하여 업데이트를 받을 수도 있습니다.

이제 패턴들을 소개합니다!

## GoF (Gang of Four): 원칙

- [상속보다 컴포지션 원칙](gang-of-four/composition-over-inheritance/index.qmd)

## 파이썬 특정 패턴

- [전역 객체 패턴](python/module-globals/index.qmd)
- [사전 바인딩된 메서드 패턴](python/prebound-methods/index.qmd)
- [감시 객체 패턴](python/sentinel-object/index.qmd)

## GoF (Gang of Four): 생성 패턴

- [추상 팩토리 패턴](gang-of-four/abstract-factory/index.qmd)
- [빌더 패턴](gang-of-four/builder/index.qmd)
- [팩토리 메서드 패턴](gang-of-four/factory-method/index.qmd)
- [프로토타입 패턴](gang-of-four/prototype/index.qmd)
- [싱글턴 패턴](gang-of-four/singleton/index.qmd)

## GoF (Gang of Four): 구조 패턴

- [컴포지트 패턴](gang-of-four/composite/index.qmd)
- [데코레이터 패턴](gang-of-four/decorator-pattern/index.qmd)
- [플라이웨이트 패턴](gang-of-four/flyweight/index.qmd)

## GoF (Gang of Four): 행동 패턴

- [반복자 패턴](gang-of-four/iterator/index.qmd)

## 참고 문헌

- [Gang of Four 책](gang-of-four/index.qmd)
- [마틴 파울러의 리팩토링](fowler-refactoring/index.qmd)
